name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install black isort mypy flake8 pytest pytest-cov

      - name: Run format check
        run: black --check .

      - name: Run import sort check
        run: isort --check-only .

      - name: Run mypy
        run: PYTHONPATH=app mypy .

      - name: Run flake8
        run: flake8 .

      - name: Run tests with coverage
        run: pytest --cov=app --cov-report=term
